steps:
- id: 'build-status'
  name: 'alpine'
  entrypoint: 'sh'
  dir: /workspace
  args:
  - '-c'
  - |
      echo "***********************"
      echo ""
      echo "$PROJECT_ID"
      echo "$PROJECT_NUMBER"
      echo "$BUILD_ID"
      echo "$LOCATION"
      echo ""
      echo "***********************"

# Build and push docker image to Artifact Registry
- id: 'docker-build-push'
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/workstations/${_IMAGE}:${BUILD_ID}', '-f', '${DOCKERFILE_PATH}', '.' ]

serviceAccount: 'projects/${PROJECT_ID}/serviceAccounts/${PROJECT_NUMBER}-compute@developer.gserviceaccount.com'
images:
- '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/workstations/${_IMAGE}:${BUILD_ID}'
options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _LOCATION: us-central1
  _IMAGE: vscider
  _DOCKERFILE_PATH: './code-oss-ext/Dockerfile'
